name: Bug Report
description: Report a bug or issue
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's the bug?
      placeholder: Describe the issue
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run command X
        2. Observe error Y
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Version, OS, etc.
      placeholder: |
        - PPDS CLI version: 1.0.0-beta.10
        - OS: Windows 11
        - .NET version: 8.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or stack traces
      render: shell
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity (optional - will be set during triage)
      description: How severe is this bug?
      options:
        - P0-Critical (crash, data loss, security)
        - P1-High (major functionality broken)
        - P2-Medium (functionality impaired)
        - P3-Low (minor issue, workaround exists)
    validations:
      required: false

  - type: dropdown
    id: size
    attributes:
      label: Fix Complexity (optional)
      description: Rough estimate of fix effort
      options:
        - XS (< 1 hour)
        - S (1-4 hours)
        - M (1-2 days)
        - L (3-5 days)
        - XL (1+ week)
    validations:
      required: false
